#!/usr/bin/env python3
"""shortLink setup helper.

Generates a cryptographically secure admin token and writes a `.env`
file ready for use with the shortlink server and CLI.

Examples
--------
    # Use defaults: writes ./.env with a fresh admin token.
    python3 deploy/setup.py

    # Name the deployment and pre-fill the public base URL.
    python3 deploy/setup.py --campaign summer-sale \\
        --base-url https://links.example.com --init
"""

from __future__ import annotations

import argparse
import os
import re
import secrets
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

CAMPAIGN_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def generate_admin_token() -> str:
    """Return a 32-byte URL-safe random token (~43 base64 chars, ~256 bits)."""
    return secrets.token_urlsafe(32)


def validate_base_url(raw: str) -> str:
    parsed = urlparse(raw)
    if parsed.scheme not in ("http", "https"):
        raise argparse.ArgumentTypeError(
            f"base URL must be http:// or https://, got {parsed.scheme or '(no scheme)'!r}"
        )
    if not parsed.netloc:
        raise argparse.ArgumentTypeError("base URL must include a host")
    return raw.rstrip("/")


def validate_campaign(raw: str) -> str:
    if not CAMPAIGN_PATTERN.match(raw):
        raise argparse.ArgumentTypeError(
            "campaign must match [A-Za-z0-9][A-Za-z0-9._-]{0,63}"
        )
    return raw


def build_env(
    campaign: str | None,
    base_url: str,
    admin_token: str,
    db_path: Path,
    slug_length: int,
    enable_docs: bool,
) -> str:
    lines: list[str] = ["# Generated by deploy/setup.py. Do not commit this file."]
    if campaign:
        lines.append(f"# Campaign: {campaign}")
    lines.append("")
    lines.append(f"SHORTLINK_BASE_URL={base_url}")
    lines.append(f"SHORTLINK_ADMIN_TOKEN={admin_token}")
    lines.append(f"SHORTLINK_DB_PATH={db_path}")
    lines.append(f"SHORTLINK_SLUG_LENGTH={slug_length}")
    lines.append(f"SHORTLINK_ENABLE_DOCS={'1' if enable_docs else '0'}")
    return "\n".join(lines) + "\n"


def write_env_secure(path: Path, content: str) -> None:
    """Write content to path with mode 0600, replacing any existing file atomically."""
    # Re-create from scratch so an existing world-readable file can't leak the
    # new token through its previous permissions.
    if path.exists() or path.is_symlink():
        path.unlink()
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)
    # Defensive chmod: umask cannot widen the mode beyond what we requested
    # at create time, but an inherited ACL might. Force 0600 either way.
    os.chmod(path, 0o600)


def run_init(db_path: Path) -> int:
    env = os.environ.copy()
    env["SHORTLINK_DB_PATH"] = str(db_path)
    try:
        subprocess.run(["shortlink", "init"], env=env, check=True)
    except FileNotFoundError:
        print(
            "warning: 'shortlink' executable not found on PATH; "
            "install the package with `pip install -e .` or `pipx install .` "
            "and rerun `shortlink init` manually.",
            file=sys.stderr,
        )
        return 0
    except subprocess.CalledProcessError as exc:
        print(f"shortlink init failed with exit code {exc.returncode}", file=sys.stderr)
        return exc.returncode
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a shortLink admin token and write a .env file.",
    )
    parser.add_argument(
        "--campaign",
        type=validate_campaign,
        help="Optional campaign label (used as a header comment and as the "
             "default sqlite filename).",
    )
    parser.add_argument(
        "--base-url",
        type=validate_base_url,
        default="http://localhost:8000",
        help="Public base URL the CLI uses when printing short links.",
    )
    parser.add_argument(
        "--db-path",
        type=Path,
        default=None,
        help="SQLite database path (defaults to ./shortlink.sqlite, "
             "or ./<campaign>.sqlite if --campaign is set).",
    )
    parser.add_argument(
        "--slug-length",
        type=int,
        default=4,
        help="Length of auto-generated base62 slugs (default: 4).",
    )
    parser.add_argument(
        "--enable-docs",
        action="store_true",
        help="Expose /docs, /redoc and /openapi.json in the running server.",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=Path(".env"),
        help="Output path for the env file (default: ./.env).",
    )
    parser.add_argument(
        "-f", "--force",
        action="store_true",
        help="Overwrite an existing env file at --output.",
    )
    parser.add_argument(
        "--init",
        action="store_true",
        help="Run `shortlink init` after writing the env file.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Do not print the generated token to stdout.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.slug_length < 1 or args.slug_length > 32:
        print("--slug-length must be between 1 and 32", file=sys.stderr)
        return 2

    if args.output.exists() and not args.force:
        print(
            f"refusing to overwrite existing {args.output} (pass --force to replace)",
            file=sys.stderr,
        )
        return 1

    db_path = args.db_path or Path(
        f"./{args.campaign}.sqlite" if args.campaign else "./shortlink.sqlite"
    )
    admin_token = generate_admin_token()
    env_text = build_env(
        campaign=args.campaign,
        base_url=args.base_url,
        admin_token=admin_token,
        db_path=db_path,
        slug_length=args.slug_length,
        enable_docs=args.enable_docs,
    )
    write_env_secure(args.output, env_text)

    print(f"wrote {args.output} (mode 0600)")
    if not args.quiet:
        print(f"  SHORTLINK_ADMIN_TOKEN = {admin_token}")
        print("  Store this token securely; it grants full admin access.")

    if args.init:
        return run_init(db_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
